export const skillColors = {
  "C++": "group-hover:text-[#00599C]",
  "C#": "group-hover:text-[#9B4F96]",
  "Visual Basic": "group-hover:text-[#512BD4]",
  HTML: "group-hover:text-[#E34F26]",
  CSS: "group-hover:text-[#663399]",
  JavaScript: "group-hover:text-[#F7DF1E]",
  TypeScript: "group-hover:text-[#3178C6]",
  Python: "group-hover:text-[#3776AB]",
  Dart: "group-hover:text-[#0175C2]",
  Bootstrap: "group-hover:text-[#7952B3]",
  Tailwind: "group-hover:text-[#06B6D4]",
  "Material UI": "group-hover:text-[#007FFF]",
  React: "group-hover:text-[#61DAFB]",
  Astro: "group-hover:text-[#BC52EE]",
  Vite: "group-hover:text-[#646CFF]",
  Jinja: "group-hover:text-[#7E0C1B]",
  Django: "group-hover:text-[#092E20]",
  Supabase: "group-hover:text-[#3FCF8E]",
  ".NET": "group-hover:text-[#512BD4]",
  "React Router": "group-hover:text-[#CA4245]",
  MySQL: "group-hover:text-[#4479A1]",
  SQLite: "group-hover:text-[#003B57]",
  JSON: "group-hover:text-[#000000]",
  Mongodb: "group-hover:text-[#47A248]",
  Flet: "group-hover:text-[#EE3167]",
  Flutter: "group-hover:text-[#02569B]",
  WinForms: "group-hover:text-[#07f9a2]",
  Turso: "group-hover:text-[#4FF8D2]",
  "Next JS": "group-hover:text-[#000000]",
  "Nest JS": "group-hover:text-[#E0234E]",
};

export const skillsData = {
  lenguajes: [
    { name: "C++", icon: "cpp" },
    { name: "C#", icon: "csharp" },
    { name: "Visual Basic", icon: "vb" },
    { name: "HTML", icon: "html5" },
    { name: "CSS", icon: "css3" },
    { name: "JavaScript", icon: "javascript" },
    { name: "TypeScript", icon: "typescript" },
    { name: "Python", icon: "python" },
    { name: "Dart", icon: "dart" },
  ],
  frontend: [
    { name: "WinForms", icon: "code" },
    // { name: "Bootstrap", icon: "bootstrap" },
    { name: "Next JS", icon: "nextjs" },
    { name: "React", icon: "react" },
    { name: "Material UI", icon: "mui" },
    { name: "Vite", icon: "vite" },
    { name: "Tailwind", icon: "tailwind" },
    { name: "Astro", icon: "astro" },
    { name: "Flutter", icon: "flutter" },
    { name: "Flet", icon: "flet" },
  ],
  backend: [
    { name: ".NET", icon: "dotnet" },
    { name: "React Router", icon: "reactrouter" },
    { name: "Django", icon: "django" },
    { name: "Jinja", icon: "jinja" },
    // { name: "Supabase", icon: "supabase" },
    { name: "Nest JS", icon: "nestjs" },
  ],
  databases: [
    { name: "MySQL", icon: "mysql" },
    { name: "SQLite", icon: "sqlite" },
    { name: "JSON", icon: "json" },
    { name: "Supabase", icon: "supabase" },
    { name: "Mongodb", icon: "mongodb" },
    { name: "Turso", icon: "turso" },
  ],
};